### ISSUE TITLE
Error when downloading asset from S3 bucket

### ISSUE THREAD

**Issue by drnextgis** [stac-utils/stac-asset#41]
I am attempting to download approximately 500 assets from our private catalog, but every time I initiate the process, I encounter a recurring list of errors as follows:
```
$ stac-client search https://stac-catalog --query "oid=5fa4da84-75fd-44d0-9571-f053659473a0--157143" | stac-asset download --s3-requester-pays -i analytic
Traceback (most recent call last):
  File "/home/dp2/env/bin/stac-asset", line 8, in <module>
    sys.exit(cli())
  File "/home/dp2/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/dp2/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/dp2/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dp2/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dp2/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/dp2/env/lib/python3.10/site-packages/stac_asset/_cli.py", line 113, in download
    output = asyncio.run(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/dp2/env/lib/python3.10/site-packages/stac_asset/functions.py", line 114, in download_item_collection
    return await client.download_item_collection(
  File "/home/dp2/env/lib/python3.10/site-packages/stac_asset/client.py", line 309, in download_item_collection
    raise DownloadError(exceptions)
 
error when downloading asset 'analytic' with href 's3://***/20230720_133146_SN31_0_3_5_31N_429_4604.tif': Could not connect to the endpoint URL: "https://***/20230720_133146_SN31_0_3_5_31N_429_4604.tif"
error when downloading asset 'analytic' with href ...
```

It always downloads about ~470 items out of 525:

```
$ target ls -l | wc -l                                                                                                                                                                           
525
$ target find . -type f -name "*.tif" | wc -l
479
```

Do any of these details sound familiar? Could it be possible that a short-lived token is expiring during the download procedure?

When I limit the filter to yield fewer items, everything functions as intended. Consequently, I can download the required data in two attempts.

**Comment by gadomski** [comment]
> Do any of these details sound familiar? Could it be possible that a short-lived token is expiring during the download procedure?

Yes, I've had other reports of throttling screwing up other many-file downloads in a similar sort of setup. We can add some retry+rate-limiting to try to make things more robust. I'll use this ticket to track that request. Thanks for the report -- if you are able to do something similar with a public endpoint (e.g. USGS's Landsat) that would help development, but it's not required.

**Comment by gadomski** [comment]
@drnextgis any chance you can try https://github.com/stac-utils/stac-asset/pull/47 to see if it fixes your issue? There's been some breaking changes to **main** since v0.1.1 so apologies in advance for any problems.
